###########
# Project #
###########

project:
  type: "book"
  output-dir: "default_book"

book:
  title: "Single-cell analysis results"
  subtitle: "bfx1234"
  chapters:
  - "index.qmd"
  - "modules/1_read_data/read_data.qmd"
  - "modules/2_preprocessing/rna/preprocessing.qmd"
  - "modules/3_normalization/rna/normalization.qmd"
  - "modules/4_integration/rna/integration.qmd"
  - "references.qmd"

####################
# Execute defaults #
####################

execute: 
  freeze: "auto"
  echo: true
  message: true
  warning: true

##########
# Params #
##########

params:
  general:
    # Verbose
    verbose: true
    
    # Project ID
    project_id: "pbmc"
    
    # Species
    species: "homo_sapiens"
    
    # Ensembl version
    ensembl: 98
    
  modules:
    read_data:
      paramB: "E"

# params:
#   # Author
#   author: !r Sys.info()[["user"]]
# 
#   
#   project_id: pbmc
#    
#   # Path to input data
#   path_data: !r data.frame(name=c("pbmc_10x","pbmc_smartseq2"), 
#                            type=c("10x","smartseq2"), 
#                            path=c("test_datasets/10x_SmartSeq2_pbmc_GSE132044/counts/10x/", "test_datasets/10x_SmartSeq2_pbmc_GSE132044/counts/smartseq2/counts_table.tsv.gz"), 
#                            stats=c(NA, NA))
# 
#   # Data type ("RNA", "Spatial")
#   assay_raw: "RNA"
#   
#   # Downsample data to at most n cells per sample AFTER filtering (mainly for tests)
#   #   NULL to deactivate
#   downsample_cells_n: NULL
#   
#   # Downsample all samples equally according to the smallest sample
#   #   TRUE/FALSE
#   #   Overwritten by downsample_cells_n
#   downsample_cells_equally: FALSE
# 
#   # Path to output directory
#   path_out: test_datasets/10x_SmartSeq2_pbmc_GSE132044/results/
# 
#   # Marker genes based on literature, translated to Ensembl IDs
#   #   xlsx file, one list per column, first row as header and Ensembl IDs below
#   #   NULL if no known marker genes should be plotted
#   file_known_markers: test_datasets/10x_SmartSeq2_pbmc_GSE132044/known_markers.xlsx
# 
#   # Contaminant cells
#   #   NULL if not cells are to be excluded
#   #   Otherwise a file with one column, one cell name per line
#   file_contam_cells: NULL
# 
#   # Annotation via biomaRt
#   mart_dataset: hsapiens_gene_ensembl
#   annot_version: 98
#   annot_main: !r c(ensembl="ensembl_gene_id", symbol="external_gene_name", entrez="entrezgene_accession")
#   mart_attributes: !r c(c(ensembl="ensembl_gene_id", symbol="external_gene_name", entrez="entrezgene_accession"), 
#                         c("chromosome_name", "start_position", "end_position", "percentage_gene_gc_content", "gene_biotype", "strand", "description"))
#   biomart_mirror: NULL
# 
#   # Prefix for mitochondrial genes 
#   mt: "^MT-"
#   
#   # Name for doublet scores
#   # Doublet scores can be provided automatically via metadata.tsv.gz in path_data
#   # NULL if no doublet scores are provided in metadata
#   doublets: NULL
#   doublets_prediction: NULL

